export enum UserPermissionEnum {
  // USER
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  UPDATE_USER_ROLE = 'UPDATE_USER_ROLE',
  UPDATE_USER_STATUS = 'UPDATE_USER_STATUS',
  ASSIGN_PERMISSIONS = 'ASSIGN_PERMISSIONS',

  // ORGANIZATION
  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',
  UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION',
  DELETE_ORGANIZATION = 'DELETE_ORGANIZATION',

  // REPORTS
  MANAGE_REPORTS = 'MANAGE_REPORTS',
  PUBLISH_REPORTS = 'PUBLISH_REPORTS',
  CREAT_REPORTS = 'CREATE_REPORTS',
  DELETE_REPORTS = 'DELETE_REPORTS',
  UPDATE_REPORTS = 'UPDATE_REPORTS',

  // HANDBOOKS & SUMMARIES
  MANAGE_HANDBOOKS_AND_SUMMARIES = 'MANAGE_HANDBOOKS_AND_SUMMARIES',

  SUPER = 'SUPER',
}
